[package]
name = "async-sqlx-session"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "sqlx session store for async-session"
readme = "README.md"
repository = "https://github.com/jbr/async-sqlx-session"
documentation = "https://docs.rs/async-sqlx-session"
license = "MIT OR Apache-2.0"
keywords = ["sessions", "tide", "async-session", "sqlx", "sqlite"]
categories = ["web-programming::http-server", "web-programming", "database"]


[features]
default = ["sqlite"]
sqlite = ["sqlx/sqlite"]

[dependencies]
async-session = "2.0.0"
sqlx = { version = "0.3.5" }
async-std = "1.6.2"


[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
