[package]
name = "async-sqlx-session"
version = "0.3.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "sqlx session store for async-session"
readme = "README.md"
repository = "https://github.com/jbr/async-sqlx-session"
documentation = "https://docs.rs/async-sqlx-session"
license = "MIT OR Apache-2.0"
keywords = ["sessions", "tide", "async-session", "sqlx", "sqlite"]
categories = ["web-programming::http-server", "web-programming", "database"]

[package.metadata.docs.rs]
features = ["pg", "sqlite"]

[features]
default = ["native-tls"]
sqlite = ["sqlx/sqlite"]
pg = ["sqlx/postgres", "sqlx/json"]
native-tls = ["sqlx/runtime-async-std-native-tls"]
rustls = ["sqlx/runtime-async-std-rustls"]

[dependencies]
async-session = "2.0.1"
sqlx = { version = "0.4.2", features = ["chrono"] }
async-std = "1.9.0"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
